# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: document-storage-service
  namespace: document-storage
spec:
  selector:
    app: document-storage-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

